/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 93
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 79
#define ALIAS_COUNT 0
#define TOKEN_COUNT 45
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_func = 1,
  anon_sym_DASH_GT = 2,
  sym_identifier = 3,
  anon_sym_LPAREN = 4,
  anon_sym_COMMA = 5,
  anon_sym_RPAREN = 6,
  anon_sym_u8 = 7,
  anon_sym_i8 = 8,
  anon_sym_u16 = 9,
  anon_sym_i16 = 10,
  anon_sym_u32 = 11,
  anon_sym_i32 = 12,
  anon_sym_u64 = 13,
  anon_sym_i64 = 14,
  anon_sym_f32 = 15,
  anon_sym_f64 = 16,
  anon_sym_LBRACE = 17,
  anon_sym_RBRACE = 18,
  sym_oneline_comment = 19,
  sym_multiline_comment = 20,
  anon_sym_SEMI = 21,
  anon_sym_LT = 22,
  anon_sym_GT = 23,
  anon_sym_LT_EQ = 24,
  anon_sym_GT_EQ = 25,
  anon_sym_EQ_EQ = 26,
  anon_sym_EQ = 27,
  anon_sym_PLUS = 28,
  anon_sym_DASH = 29,
  anon_sym_STAR = 30,
  anon_sym_SLASH = 31,
  anon_sym_PERCENT = 32,
  sym_integer_literal = 33,
  sym_floating_point_literal = 34,
  sym_string_literal = 35,
  anon_sym_var = 36,
  anon_sym_let = 37,
  anon_sym_COLON = 38,
  anon_sym_return = 39,
  anon_sym_break = 40,
  anon_sym_loop = 41,
  anon_sym_if = 42,
  anon_sym_elif = 43,
  anon_sym_else = 44,
  sym_source_file = 45,
  sym__definition = 46,
  sym__declaration = 47,
  sym_function_definition = 48,
  sym_parameter_list = 49,
  sym__type = 50,
  sym_builtin_type = 51,
  sym_user_type = 52,
  sym_block = 53,
  sym__comment = 54,
  sym__sentence = 55,
  sym_expression_sentence = 56,
  sym_variable_declaration_sentence = 57,
  sym_variable_definition_sentence = 58,
  sym__callable_expression = 59,
  sym__uncallable_expression = 60,
  sym__expression = 61,
  sym_function_call = 62,
  sym_binary_expresion = 63,
  sym__literal = 64,
  sym_variable_reference_expression = 65,
  sym_variable_declaration = 66,
  sym_variable_definition = 67,
  sym_return_sentence = 68,
  sym_break_sentence = 69,
  sym_loop_statement = 70,
  sym_if_statement = 71,
  sym_elif_statement = 72,
  sym_else_statement = 73,
  sym__blocky = 74,
  aux_sym_source_file_repeat1 = 75,
  aux_sym_parameter_list_repeat1 = 76,
  aux_sym_block_repeat1 = 77,
  aux_sym_function_call_repeat1 = 78,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_func] = "func",
  [anon_sym_DASH_GT] = "->",
  [sym_identifier] = "identifier",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_u8] = "u8",
  [anon_sym_i8] = "i8",
  [anon_sym_u16] = "u16",
  [anon_sym_i16] = "i16",
  [anon_sym_u32] = "u32",
  [anon_sym_i32] = "i32",
  [anon_sym_u64] = "u64",
  [anon_sym_i64] = "i64",
  [anon_sym_f32] = "f32",
  [anon_sym_f64] = "f64",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_oneline_comment] = "oneline_comment",
  [sym_multiline_comment] = "multiline_comment",
  [anon_sym_SEMI] = ";",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_EQ] = "=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [sym_integer_literal] = "integer_literal",
  [sym_floating_point_literal] = "floating_point_literal",
  [sym_string_literal] = "string_literal",
  [anon_sym_var] = "var",
  [anon_sym_let] = "let",
  [anon_sym_COLON] = ":",
  [anon_sym_return] = "return",
  [anon_sym_break] = "break",
  [anon_sym_loop] = "loop",
  [anon_sym_if] = "if",
  [anon_sym_elif] = "elif",
  [anon_sym_else] = "else",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym__declaration] = "_declaration",
  [sym_function_definition] = "function_definition",
  [sym_parameter_list] = "parameter_list",
  [sym__type] = "_type",
  [sym_builtin_type] = "builtin_type",
  [sym_user_type] = "user_type",
  [sym_block] = "block",
  [sym__comment] = "_comment",
  [sym__sentence] = "_sentence",
  [sym_expression_sentence] = "expression_sentence",
  [sym_variable_declaration_sentence] = "variable_declaration_sentence",
  [sym_variable_definition_sentence] = "variable_definition_sentence",
  [sym__callable_expression] = "_callable_expression",
  [sym__uncallable_expression] = "_uncallable_expression",
  [sym__expression] = "_expression",
  [sym_function_call] = "function_call",
  [sym_binary_expresion] = "binary_expresion",
  [sym__literal] = "_literal",
  [sym_variable_reference_expression] = "variable_reference_expression",
  [sym_variable_declaration] = "variable_declaration",
  [sym_variable_definition] = "variable_definition",
  [sym_return_sentence] = "return_sentence",
  [sym_break_sentence] = "break_sentence",
  [sym_loop_statement] = "loop_statement",
  [sym_if_statement] = "if_statement",
  [sym_elif_statement] = "elif_statement",
  [sym_else_statement] = "else_statement",
  [sym__blocky] = "_blocky",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_function_call_repeat1] = "function_call_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_func] = anon_sym_func,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [sym_identifier] = sym_identifier,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_u8] = anon_sym_u8,
  [anon_sym_i8] = anon_sym_i8,
  [anon_sym_u16] = anon_sym_u16,
  [anon_sym_i16] = anon_sym_i16,
  [anon_sym_u32] = anon_sym_u32,
  [anon_sym_i32] = anon_sym_i32,
  [anon_sym_u64] = anon_sym_u64,
  [anon_sym_i64] = anon_sym_i64,
  [anon_sym_f32] = anon_sym_f32,
  [anon_sym_f64] = anon_sym_f64,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_oneline_comment] = sym_oneline_comment,
  [sym_multiline_comment] = sym_multiline_comment,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [sym_integer_literal] = sym_integer_literal,
  [sym_floating_point_literal] = sym_floating_point_literal,
  [sym_string_literal] = sym_string_literal,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_break] = anon_sym_break,
  [anon_sym_loop] = anon_sym_loop,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_elif] = anon_sym_elif,
  [anon_sym_else] = anon_sym_else,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym__declaration] = sym__declaration,
  [sym_function_definition] = sym_function_definition,
  [sym_parameter_list] = sym_parameter_list,
  [sym__type] = sym__type,
  [sym_builtin_type] = sym_builtin_type,
  [sym_user_type] = sym_user_type,
  [sym_block] = sym_block,
  [sym__comment] = sym__comment,
  [sym__sentence] = sym__sentence,
  [sym_expression_sentence] = sym_expression_sentence,
  [sym_variable_declaration_sentence] = sym_variable_declaration_sentence,
  [sym_variable_definition_sentence] = sym_variable_definition_sentence,
  [sym__callable_expression] = sym__callable_expression,
  [sym__uncallable_expression] = sym__uncallable_expression,
  [sym__expression] = sym__expression,
  [sym_function_call] = sym_function_call,
  [sym_binary_expresion] = sym_binary_expresion,
  [sym__literal] = sym__literal,
  [sym_variable_reference_expression] = sym_variable_reference_expression,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_variable_definition] = sym_variable_definition,
  [sym_return_sentence] = sym_return_sentence,
  [sym_break_sentence] = sym_break_sentence,
  [sym_loop_statement] = sym_loop_statement,
  [sym_if_statement] = sym_if_statement,
  [sym_elif_statement] = sym_elif_statement,
  [sym_else_statement] = sym_else_statement,
  [sym__blocky] = sym__blocky,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_function_call_repeat1] = aux_sym_function_call_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_func] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_oneline_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_multiline_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_floating_point_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_break] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_loop] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_builtin_type] = {
    .visible = true,
    .named = true,
  },
  [sym_user_type] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__comment] = {
    .visible = false,
    .named = true,
  },
  [sym__sentence] = {
    .visible = false,
    .named = true,
  },
  [sym_expression_sentence] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration_sentence] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_definition_sentence] = {
    .visible = true,
    .named = true,
  },
  [sym__callable_expression] = {
    .visible = false,
    .named = true,
  },
  [sym__uncallable_expression] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expresion] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_variable_reference_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_return_sentence] = {
    .visible = true,
    .named = true,
  },
  [sym_break_sentence] = {
    .visible = true,
    .named = true,
  },
  [sym_loop_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_elif_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_else_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__blocky] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_call_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_name = 2,
  field_parameters = 3,
  field_return_type = 4,
  field_type = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_name] = "name",
  [field_parameters] = "parameters",
  [field_return_type] = "return_type",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
    {field_type, 3},
  [2] =
    {field_body, 5},
    {field_name, 1},
    {field_parameters, 2},
    {field_return_type, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 2,
  [5] = 5,
  [6] = 3,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 15,
  [61] = 13,
  [62] = 14,
  [63] = 63,
  [64] = 16,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 77,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 86,
  [92] = 92,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(42);
      ADVANCE_MAP(
        '"', 3,
        '#', 104,
        '%', 119,
        '(', 77,
        ')', 79,
        '*', 117,
        '+', 114,
        ',', 78,
        '-', 116,
        '/', 118,
        ':', 128,
        ';', 107,
        '<', 108,
        '=', 113,
        '>', 109,
        'b', 36,
        'e', 30,
        'f', 13,
        'i', 8,
        'l', 23,
        'r', 26,
        'u', 9,
        'v', 21,
        '{', 100,
        '}', 101,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(120);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 3,
        '#', 104,
        '%', 119,
        '(', 77,
        ')', 79,
        '*', 117,
        '+', 114,
        ',', 78,
        '-', 115,
        '/', 118,
        ';', 107,
        '<', 108,
        '=', 113,
        '>', 109,
        'b', 72,
        'e', 66,
        'i', 62,
        'l', 58,
        'r', 61,
        'v', 57,
        '{', 100,
        '}', 101,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(120);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '(') ADVANCE(77);
      if (lookahead == ')') ADVANCE(79);
      if (lookahead == ';') ADVANCE(107);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(120);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(122);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(123);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(106);
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(19);
      if (lookahead == 'f') ADVANCE(50);
      if (lookahead == 'i') ADVANCE(45);
      if (lookahead == 'u') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 8:
      if (lookahead == '1') ADVANCE(17);
      if (lookahead == '3') ADVANCE(11);
      if (lookahead == '6') ADVANCE(15);
      if (lookahead == '8') ADVANCE(82);
      if (lookahead == 'f') ADVANCE(135);
      END_STATE();
    case 9:
      if (lookahead == '1') ADVANCE(18);
      if (lookahead == '3') ADVANCE(12);
      if (lookahead == '6') ADVANCE(16);
      if (lookahead == '8') ADVANCE(80);
      END_STATE();
    case 10:
      if (lookahead == '2') ADVANCE(96);
      END_STATE();
    case 11:
      if (lookahead == '2') ADVANCE(90);
      END_STATE();
    case 12:
      if (lookahead == '2') ADVANCE(88);
      END_STATE();
    case 13:
      if (lookahead == '3') ADVANCE(10);
      if (lookahead == '6') ADVANCE(14);
      if (lookahead == 'u') ADVANCE(31);
      END_STATE();
    case 14:
      if (lookahead == '4') ADVANCE(98);
      END_STATE();
    case 15:
      if (lookahead == '4') ADVANCE(94);
      END_STATE();
    case 16:
      if (lookahead == '4') ADVANCE(92);
      END_STATE();
    case 17:
      if (lookahead == '6') ADVANCE(86);
      END_STATE();
    case 18:
      if (lookahead == '6') ADVANCE(84);
      END_STATE();
    case 19:
      if (lookahead == '>') ADVANCE(44);
      END_STATE();
    case 20:
      if (lookahead == 'a') ADVANCE(29);
      END_STATE();
    case 21:
      if (lookahead == 'a') ADVANCE(35);
      END_STATE();
    case 22:
      if (lookahead == 'c') ADVANCE(43);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(38);
      if (lookahead == 'o') ADVANCE(33);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(139);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 27:
      if (lookahead == 'f') ADVANCE(137);
      END_STATE();
    case 28:
      if (lookahead == 'i') ADVANCE(27);
      if (lookahead == 's') ADVANCE(24);
      END_STATE();
    case 29:
      if (lookahead == 'k') ADVANCE(131);
      END_STATE();
    case 30:
      if (lookahead == 'l') ADVANCE(28);
      END_STATE();
    case 31:
      if (lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 32:
      if (lookahead == 'n') ADVANCE(129);
      END_STATE();
    case 33:
      if (lookahead == 'o') ADVANCE(34);
      END_STATE();
    case 34:
      if (lookahead == 'p') ADVANCE(133);
      END_STATE();
    case 35:
      if (lookahead == 'r') ADVANCE(124);
      END_STATE();
    case 36:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 37:
      if (lookahead == 'r') ADVANCE(32);
      END_STATE();
    case 38:
      if (lookahead == 't') ADVANCE(126);
      END_STATE();
    case 39:
      if (lookahead == 't') ADVANCE(40);
      END_STATE();
    case 40:
      if (lookahead == 'u') ADVANCE(37);
      END_STATE();
    case 41:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(121);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_func);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '1') ADVANCE(54);
      if (lookahead == '3') ADVANCE(48);
      if (lookahead == '6') ADVANCE(52);
      if (lookahead == '8') ADVANCE(83);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '1') ADVANCE(55);
      if (lookahead == '3') ADVANCE(49);
      if (lookahead == '6') ADVANCE(53);
      if (lookahead == '8') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '2') ADVANCE(97);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '2') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '2') ADVANCE(89);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '3') ADVANCE(47);
      if (lookahead == '6') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '4') ADVANCE(99);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '4') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '4') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '6') ADVANCE(87);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '6') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(73);
      if (lookahead == 'o') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(140);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(136);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(138);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(63);
      if (lookahead == 's') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'k') ADVANCE(132);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(130);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(134);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(125);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(127);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_u8);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_u8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_i8);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_i8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_u16);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_u16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_i16);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_i16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_u32);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_u32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_i32);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_i32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_u64);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_u64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_i64);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_i64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_f32);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_f32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_f64);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_f64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_oneline_comment);
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '#') ADVANCE(103);
      if (lookahead == '*') ADVANCE(102);
      if (lookahead != 0) ADVANCE(103);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_oneline_comment);
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '*') ADVANCE(102);
      if (lookahead != 0) ADVANCE(103);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_oneline_comment);
      if (lookahead == '*') ADVANCE(103);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(105);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_oneline_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(105);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_multiline_comment);
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(110);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(111);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(112);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(44);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(120);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_floating_point_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(121);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_string_literal);
      if (lookahead == '"') ADVANCE(122);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_var);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(anon_sym_break);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(anon_sym_break);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(anon_sym_loop);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(anon_sym_loop);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(anon_sym_elif);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(anon_sym_elif);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(anon_sym_else);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 7},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 7},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 2},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 2},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 7},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 7},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 7},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_func] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_u8] = ACTIONS(1),
    [anon_sym_i8] = ACTIONS(1),
    [anon_sym_u16] = ACTIONS(1),
    [anon_sym_i16] = ACTIONS(1),
    [anon_sym_u32] = ACTIONS(1),
    [anon_sym_i32] = ACTIONS(1),
    [anon_sym_u64] = ACTIONS(1),
    [anon_sym_i64] = ACTIONS(1),
    [anon_sym_f32] = ACTIONS(1),
    [anon_sym_f64] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_oneline_comment] = ACTIONS(1),
    [sym_multiline_comment] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
    [sym_floating_point_literal] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_break] = ACTIONS(1),
    [anon_sym_loop] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_elif] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(79),
    [sym__definition] = STATE(41),
    [sym__declaration] = STATE(41),
    [sym_function_definition] = STATE(41),
    [sym_variable_declaration_sentence] = STATE(41),
    [sym_variable_definition_sentence] = STATE(41),
    [sym_variable_declaration] = STATE(78),
    [sym_variable_definition] = STATE(86),
    [aux_sym_source_file_repeat1] = STATE(41),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_func] = ACTIONS(5),
    [anon_sym_var] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym_block] = STATE(5),
    [sym__comment] = STATE(5),
    [sym__sentence] = STATE(5),
    [sym_expression_sentence] = STATE(5),
    [sym_variable_declaration_sentence] = STATE(5),
    [sym_variable_definition_sentence] = STATE(5),
    [sym__callable_expression] = STATE(21),
    [sym__uncallable_expression] = STATE(44),
    [sym__expression] = STATE(44),
    [sym_function_call] = STATE(21),
    [sym_binary_expresion] = STATE(44),
    [sym__literal] = STATE(44),
    [sym_variable_reference_expression] = STATE(21),
    [sym_variable_declaration] = STATE(77),
    [sym_variable_definition] = STATE(91),
    [sym_return_sentence] = STATE(5),
    [sym_break_sentence] = STATE(5),
    [sym_loop_statement] = STATE(5),
    [sym_if_statement] = STATE(5),
    [sym_elif_statement] = STATE(5),
    [sym_else_statement] = STATE(5),
    [sym__blocky] = STATE(5),
    [aux_sym_block_repeat1] = STATE(5),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(15),
    [sym_oneline_comment] = ACTIONS(17),
    [sym_multiline_comment] = ACTIONS(17),
    [sym_integer_literal] = ACTIONS(19),
    [sym_floating_point_literal] = ACTIONS(21),
    [sym_string_literal] = ACTIONS(21),
    [anon_sym_var] = ACTIONS(23),
    [anon_sym_let] = ACTIONS(23),
    [anon_sym_return] = ACTIONS(25),
    [anon_sym_break] = ACTIONS(27),
    [anon_sym_loop] = ACTIONS(29),
    [anon_sym_if] = ACTIONS(31),
    [anon_sym_elif] = ACTIONS(33),
    [anon_sym_else] = ACTIONS(35),
  },
  [STATE(3)] = {
    [sym_block] = STATE(2),
    [sym__comment] = STATE(2),
    [sym__sentence] = STATE(2),
    [sym_expression_sentence] = STATE(2),
    [sym_variable_declaration_sentence] = STATE(2),
    [sym_variable_definition_sentence] = STATE(2),
    [sym__callable_expression] = STATE(21),
    [sym__uncallable_expression] = STATE(44),
    [sym__expression] = STATE(44),
    [sym_function_call] = STATE(21),
    [sym_binary_expresion] = STATE(44),
    [sym__literal] = STATE(44),
    [sym_variable_reference_expression] = STATE(21),
    [sym_variable_declaration] = STATE(77),
    [sym_variable_definition] = STATE(91),
    [sym_return_sentence] = STATE(2),
    [sym_break_sentence] = STATE(2),
    [sym_loop_statement] = STATE(2),
    [sym_if_statement] = STATE(2),
    [sym_elif_statement] = STATE(2),
    [sym_else_statement] = STATE(2),
    [sym__blocky] = STATE(2),
    [aux_sym_block_repeat1] = STATE(2),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(37),
    [sym_oneline_comment] = ACTIONS(39),
    [sym_multiline_comment] = ACTIONS(39),
    [sym_integer_literal] = ACTIONS(19),
    [sym_floating_point_literal] = ACTIONS(21),
    [sym_string_literal] = ACTIONS(21),
    [anon_sym_var] = ACTIONS(23),
    [anon_sym_let] = ACTIONS(23),
    [anon_sym_return] = ACTIONS(25),
    [anon_sym_break] = ACTIONS(27),
    [anon_sym_loop] = ACTIONS(29),
    [anon_sym_if] = ACTIONS(31),
    [anon_sym_elif] = ACTIONS(33),
    [anon_sym_else] = ACTIONS(35),
  },
  [STATE(4)] = {
    [sym_block] = STATE(5),
    [sym__comment] = STATE(5),
    [sym__sentence] = STATE(5),
    [sym_expression_sentence] = STATE(5),
    [sym_variable_declaration_sentence] = STATE(5),
    [sym_variable_definition_sentence] = STATE(5),
    [sym__callable_expression] = STATE(21),
    [sym__uncallable_expression] = STATE(44),
    [sym__expression] = STATE(44),
    [sym_function_call] = STATE(21),
    [sym_binary_expresion] = STATE(44),
    [sym__literal] = STATE(44),
    [sym_variable_reference_expression] = STATE(21),
    [sym_variable_declaration] = STATE(77),
    [sym_variable_definition] = STATE(91),
    [sym_return_sentence] = STATE(5),
    [sym_break_sentence] = STATE(5),
    [sym_loop_statement] = STATE(5),
    [sym_if_statement] = STATE(5),
    [sym_elif_statement] = STATE(5),
    [sym_else_statement] = STATE(5),
    [sym__blocky] = STATE(5),
    [aux_sym_block_repeat1] = STATE(5),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(41),
    [sym_oneline_comment] = ACTIONS(17),
    [sym_multiline_comment] = ACTIONS(17),
    [sym_integer_literal] = ACTIONS(19),
    [sym_floating_point_literal] = ACTIONS(21),
    [sym_string_literal] = ACTIONS(21),
    [anon_sym_var] = ACTIONS(23),
    [anon_sym_let] = ACTIONS(23),
    [anon_sym_return] = ACTIONS(25),
    [anon_sym_break] = ACTIONS(27),
    [anon_sym_loop] = ACTIONS(29),
    [anon_sym_if] = ACTIONS(31),
    [anon_sym_elif] = ACTIONS(33),
    [anon_sym_else] = ACTIONS(35),
  },
  [STATE(5)] = {
    [sym_block] = STATE(5),
    [sym__comment] = STATE(5),
    [sym__sentence] = STATE(5),
    [sym_expression_sentence] = STATE(5),
    [sym_variable_declaration_sentence] = STATE(5),
    [sym_variable_definition_sentence] = STATE(5),
    [sym__callable_expression] = STATE(21),
    [sym__uncallable_expression] = STATE(44),
    [sym__expression] = STATE(44),
    [sym_function_call] = STATE(21),
    [sym_binary_expresion] = STATE(44),
    [sym__literal] = STATE(44),
    [sym_variable_reference_expression] = STATE(21),
    [sym_variable_declaration] = STATE(77),
    [sym_variable_definition] = STATE(91),
    [sym_return_sentence] = STATE(5),
    [sym_break_sentence] = STATE(5),
    [sym_loop_statement] = STATE(5),
    [sym_if_statement] = STATE(5),
    [sym_elif_statement] = STATE(5),
    [sym_else_statement] = STATE(5),
    [sym__blocky] = STATE(5),
    [aux_sym_block_repeat1] = STATE(5),
    [sym_identifier] = ACTIONS(43),
    [anon_sym_LPAREN] = ACTIONS(46),
    [anon_sym_LBRACE] = ACTIONS(49),
    [anon_sym_RBRACE] = ACTIONS(52),
    [sym_oneline_comment] = ACTIONS(54),
    [sym_multiline_comment] = ACTIONS(54),
    [sym_integer_literal] = ACTIONS(57),
    [sym_floating_point_literal] = ACTIONS(60),
    [sym_string_literal] = ACTIONS(60),
    [anon_sym_var] = ACTIONS(63),
    [anon_sym_let] = ACTIONS(63),
    [anon_sym_return] = ACTIONS(66),
    [anon_sym_break] = ACTIONS(69),
    [anon_sym_loop] = ACTIONS(72),
    [anon_sym_if] = ACTIONS(75),
    [anon_sym_elif] = ACTIONS(78),
    [anon_sym_else] = ACTIONS(81),
  },
  [STATE(6)] = {
    [sym_block] = STATE(4),
    [sym__comment] = STATE(4),
    [sym__sentence] = STATE(4),
    [sym_expression_sentence] = STATE(4),
    [sym_variable_declaration_sentence] = STATE(4),
    [sym_variable_definition_sentence] = STATE(4),
    [sym__callable_expression] = STATE(21),
    [sym__uncallable_expression] = STATE(44),
    [sym__expression] = STATE(44),
    [sym_function_call] = STATE(21),
    [sym_binary_expresion] = STATE(44),
    [sym__literal] = STATE(44),
    [sym_variable_reference_expression] = STATE(21),
    [sym_variable_declaration] = STATE(77),
    [sym_variable_definition] = STATE(91),
    [sym_return_sentence] = STATE(4),
    [sym_break_sentence] = STATE(4),
    [sym_loop_statement] = STATE(4),
    [sym_if_statement] = STATE(4),
    [sym_elif_statement] = STATE(4),
    [sym_else_statement] = STATE(4),
    [sym__blocky] = STATE(4),
    [aux_sym_block_repeat1] = STATE(4),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(84),
    [sym_oneline_comment] = ACTIONS(86),
    [sym_multiline_comment] = ACTIONS(86),
    [sym_integer_literal] = ACTIONS(19),
    [sym_floating_point_literal] = ACTIONS(21),
    [sym_string_literal] = ACTIONS(21),
    [anon_sym_var] = ACTIONS(23),
    [anon_sym_let] = ACTIONS(23),
    [anon_sym_return] = ACTIONS(25),
    [anon_sym_break] = ACTIONS(27),
    [anon_sym_loop] = ACTIONS(29),
    [anon_sym_if] = ACTIONS(31),
    [anon_sym_elif] = ACTIONS(33),
    [anon_sym_else] = ACTIONS(35),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(90), 5,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_floating_point_literal,
      sym_string_literal,
    ACTIONS(88), 12,
      sym_identifier,
      sym_oneline_comment,
      sym_multiline_comment,
      sym_integer_literal,
      anon_sym_var,
      anon_sym_let,
      anon_sym_return,
      anon_sym_break,
      anon_sym_loop,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
  [22] = 2,
    ACTIONS(94), 5,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_floating_point_literal,
      sym_string_literal,
    ACTIONS(92), 12,
      sym_identifier,
      sym_oneline_comment,
      sym_multiline_comment,
      sym_integer_literal,
      anon_sym_var,
      anon_sym_let,
      anon_sym_return,
      anon_sym_break,
      anon_sym_loop,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
  [44] = 2,
    ACTIONS(98), 5,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_floating_point_literal,
      sym_string_literal,
    ACTIONS(96), 12,
      sym_identifier,
      sym_oneline_comment,
      sym_multiline_comment,
      sym_integer_literal,
      anon_sym_var,
      anon_sym_let,
      anon_sym_return,
      anon_sym_break,
      anon_sym_loop,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
  [66] = 2,
    ACTIONS(102), 5,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_floating_point_literal,
      sym_string_literal,
    ACTIONS(100), 12,
      sym_identifier,
      sym_oneline_comment,
      sym_multiline_comment,
      sym_integer_literal,
      anon_sym_var,
      anon_sym_let,
      anon_sym_return,
      anon_sym_break,
      anon_sym_loop,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
  [88] = 2,
    ACTIONS(106), 5,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_floating_point_literal,
      sym_string_literal,
    ACTIONS(104), 12,
      sym_identifier,
      sym_oneline_comment,
      sym_multiline_comment,
      sym_integer_literal,
      anon_sym_var,
      anon_sym_let,
      anon_sym_return,
      anon_sym_break,
      anon_sym_loop,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
  [110] = 2,
    ACTIONS(110), 5,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_floating_point_literal,
      sym_string_literal,
    ACTIONS(108), 12,
      sym_identifier,
      sym_oneline_comment,
      sym_multiline_comment,
      sym_integer_literal,
      anon_sym_var,
      anon_sym_let,
      anon_sym_return,
      anon_sym_break,
      anon_sym_loop,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
  [132] = 2,
    ACTIONS(114), 5,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_floating_point_literal,
      sym_string_literal,
    ACTIONS(112), 12,
      sym_identifier,
      sym_oneline_comment,
      sym_multiline_comment,
      sym_integer_literal,
      anon_sym_var,
      anon_sym_let,
      anon_sym_return,
      anon_sym_break,
      anon_sym_loop,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
  [154] = 2,
    ACTIONS(118), 5,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_floating_point_literal,
      sym_string_literal,
    ACTIONS(116), 12,
      sym_identifier,
      sym_oneline_comment,
      sym_multiline_comment,
      sym_integer_literal,
      anon_sym_var,
      anon_sym_let,
      anon_sym_return,
      anon_sym_break,
      anon_sym_loop,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
  [176] = 2,
    ACTIONS(122), 5,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_floating_point_literal,
      sym_string_literal,
    ACTIONS(120), 12,
      sym_identifier,
      sym_oneline_comment,
      sym_multiline_comment,
      sym_integer_literal,
      anon_sym_var,
      anon_sym_let,
      anon_sym_return,
      anon_sym_break,
      anon_sym_loop,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
  [198] = 2,
    ACTIONS(126), 5,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_floating_point_literal,
      sym_string_literal,
    ACTIONS(124), 12,
      sym_identifier,
      sym_oneline_comment,
      sym_multiline_comment,
      sym_integer_literal,
      anon_sym_var,
      anon_sym_let,
      anon_sym_return,
      anon_sym_break,
      anon_sym_loop,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
  [220] = 2,
    ACTIONS(130), 5,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_floating_point_literal,
      sym_string_literal,
    ACTIONS(128), 12,
      sym_identifier,
      sym_oneline_comment,
      sym_multiline_comment,
      sym_integer_literal,
      anon_sym_var,
      anon_sym_let,
      anon_sym_return,
      anon_sym_break,
      anon_sym_loop,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
  [242] = 2,
    ACTIONS(134), 5,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_floating_point_literal,
      sym_string_literal,
    ACTIONS(132), 12,
      sym_identifier,
      sym_oneline_comment,
      sym_multiline_comment,
      sym_integer_literal,
      anon_sym_var,
      anon_sym_let,
      anon_sym_return,
      anon_sym_break,
      anon_sym_loop,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
  [264] = 2,
    ACTIONS(138), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(136), 12,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [284] = 2,
    ACTIONS(142), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(140), 12,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [304] = 3,
    ACTIONS(144), 1,
      anon_sym_LPAREN,
    ACTIONS(148), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(146), 11,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [326] = 2,
    ACTIONS(152), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(150), 12,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [346] = 2,
    ACTIONS(156), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(154), 12,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [366] = 2,
    ACTIONS(160), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(158), 12,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [386] = 2,
    ACTIONS(164), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(162), 11,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [405] = 9,
    ACTIONS(166), 1,
      anon_sym_COMMA,
    ACTIONS(168), 1,
      anon_sym_RPAREN,
    ACTIONS(174), 1,
      anon_sym_EQ_EQ,
    ACTIONS(176), 1,
      anon_sym_EQ,
    STATE(66), 1,
      aux_sym_function_call_repeat1,
    ACTIONS(170), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(172), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(178), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(180), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [438] = 6,
    ACTIONS(174), 1,
      anon_sym_EQ_EQ,
    ACTIONS(176), 1,
      anon_sym_EQ,
    ACTIONS(164), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(178), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(180), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(162), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [465] = 2,
    ACTIONS(184), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(182), 11,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [484] = 3,
    ACTIONS(164), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(180), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(162), 8,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
  [505] = 4,
    ACTIONS(178), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(164), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(180), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(162), 6,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
  [528] = 3,
    ACTIONS(186), 1,
      sym_identifier,
    STATE(63), 3,
      sym__type,
      sym_builtin_type,
      sym_user_type,
    ACTIONS(188), 10,
      anon_sym_u8,
      anon_sym_i8,
      anon_sym_u16,
      anon_sym_i16,
      anon_sym_u32,
      anon_sym_i32,
      anon_sym_u64,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
  [549] = 3,
    ACTIONS(186), 1,
      sym_identifier,
    STATE(72), 3,
      sym__type,
      sym_builtin_type,
      sym_user_type,
    ACTIONS(188), 10,
      anon_sym_u8,
      anon_sym_i8,
      anon_sym_u16,
      anon_sym_i16,
      anon_sym_u32,
      anon_sym_i32,
      anon_sym_u64,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
  [570] = 7,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(190), 1,
      sym_identifier,
    ACTIONS(192), 1,
      anon_sym_RPAREN,
    ACTIONS(194), 1,
      sym_integer_literal,
    ACTIONS(196), 2,
      sym_floating_point_literal,
      sym_string_literal,
    STATE(21), 3,
      sym__callable_expression,
      sym_function_call,
      sym_variable_reference_expression,
    STATE(26), 4,
      sym__uncallable_expression,
      sym__expression,
      sym_binary_expresion,
      sym__literal,
  [598] = 4,
    ACTIONS(144), 1,
      anon_sym_LPAREN,
    ACTIONS(198), 1,
      anon_sym_RPAREN,
    ACTIONS(148), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(146), 8,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [620] = 7,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(190), 1,
      sym_identifier,
    ACTIONS(200), 1,
      anon_sym_SEMI,
    ACTIONS(202), 1,
      sym_integer_literal,
    ACTIONS(204), 2,
      sym_floating_point_literal,
      sym_string_literal,
    STATE(21), 3,
      sym__callable_expression,
      sym_function_call,
      sym_variable_reference_expression,
    STATE(46), 4,
      sym__uncallable_expression,
      sym__expression,
      sym_binary_expresion,
      sym__literal,
  [648] = 7,
    ACTIONS(174), 1,
      anon_sym_EQ_EQ,
    ACTIONS(176), 1,
      anon_sym_EQ,
    ACTIONS(170), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(172), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(178), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(206), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(180), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [676] = 7,
    ACTIONS(174), 1,
      anon_sym_EQ_EQ,
    ACTIONS(176), 1,
      anon_sym_EQ,
    ACTIONS(208), 1,
      anon_sym_RPAREN,
    ACTIONS(170), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(172), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(178), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(180), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [703] = 6,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(190), 1,
      sym_identifier,
    ACTIONS(210), 1,
      sym_integer_literal,
    ACTIONS(212), 2,
      sym_floating_point_literal,
      sym_string_literal,
    STATE(21), 3,
      sym__callable_expression,
      sym_function_call,
      sym_variable_reference_expression,
    STATE(27), 4,
      sym__uncallable_expression,
      sym__expression,
      sym_binary_expresion,
      sym__literal,
  [728] = 6,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(190), 1,
      sym_identifier,
    ACTIONS(214), 1,
      sym_integer_literal,
    ACTIONS(216), 2,
      sym_floating_point_literal,
      sym_string_literal,
    STATE(21), 3,
      sym__callable_expression,
      sym_function_call,
      sym_variable_reference_expression,
    STATE(30), 4,
      sym__uncallable_expression,
      sym__expression,
      sym_binary_expresion,
      sym__literal,
  [753] = 6,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(190), 1,
      sym_identifier,
    ACTIONS(218), 1,
      sym_integer_literal,
    ACTIONS(220), 2,
      sym_floating_point_literal,
      sym_string_literal,
    STATE(21), 3,
      sym__callable_expression,
      sym_function_call,
      sym_variable_reference_expression,
    STATE(29), 4,
      sym__uncallable_expression,
      sym__expression,
      sym_binary_expresion,
      sym__literal,
  [778] = 6,
    ACTIONS(5), 1,
      anon_sym_func,
    ACTIONS(222), 1,
      ts_builtin_sym_end,
    STATE(78), 1,
      sym_variable_declaration,
    STATE(86), 1,
      sym_variable_definition,
    ACTIONS(7), 2,
      anon_sym_var,
      anon_sym_let,
    STATE(48), 6,
      sym__definition,
      sym__declaration,
      sym_function_definition,
      sym_variable_declaration_sentence,
      sym_variable_definition_sentence,
      aux_sym_source_file_repeat1,
  [803] = 6,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(190), 1,
      sym_identifier,
    ACTIONS(224), 1,
      sym_integer_literal,
    ACTIONS(226), 2,
      sym_floating_point_literal,
      sym_string_literal,
    STATE(21), 3,
      sym__callable_expression,
      sym_function_call,
      sym_variable_reference_expression,
    STATE(25), 4,
      sym__uncallable_expression,
      sym__expression,
      sym_binary_expresion,
      sym__literal,
  [828] = 6,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(190), 1,
      sym_identifier,
    ACTIONS(228), 1,
      sym_integer_literal,
    ACTIONS(230), 2,
      sym_floating_point_literal,
      sym_string_literal,
    STATE(21), 3,
      sym__callable_expression,
      sym_function_call,
      sym_variable_reference_expression,
    STATE(36), 4,
      sym__uncallable_expression,
      sym__expression,
      sym_binary_expresion,
      sym__literal,
  [853] = 7,
    ACTIONS(174), 1,
      anon_sym_EQ_EQ,
    ACTIONS(176), 1,
      anon_sym_EQ,
    ACTIONS(232), 1,
      anon_sym_SEMI,
    ACTIONS(170), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(172), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(178), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(180), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [880] = 6,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(190), 1,
      sym_identifier,
    ACTIONS(234), 1,
      sym_integer_literal,
    ACTIONS(236), 2,
      sym_floating_point_literal,
      sym_string_literal,
    STATE(21), 3,
      sym__callable_expression,
      sym_function_call,
      sym_variable_reference_expression,
    STATE(47), 4,
      sym__uncallable_expression,
      sym__expression,
      sym_binary_expresion,
      sym__literal,
  [905] = 7,
    ACTIONS(174), 1,
      anon_sym_EQ_EQ,
    ACTIONS(176), 1,
      anon_sym_EQ,
    ACTIONS(238), 1,
      anon_sym_SEMI,
    ACTIONS(170), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(172), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(178), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(180), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [932] = 7,
    ACTIONS(174), 1,
      anon_sym_EQ_EQ,
    ACTIONS(176), 1,
      anon_sym_EQ,
    ACTIONS(240), 1,
      anon_sym_SEMI,
    ACTIONS(170), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(172), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(178), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(180), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [959] = 6,
    ACTIONS(242), 1,
      ts_builtin_sym_end,
    ACTIONS(244), 1,
      anon_sym_func,
    STATE(78), 1,
      sym_variable_declaration,
    STATE(86), 1,
      sym_variable_definition,
    ACTIONS(247), 2,
      anon_sym_var,
      anon_sym_let,
    STATE(48), 6,
      sym__definition,
      sym__declaration,
      sym_function_definition,
      sym_variable_declaration_sentence,
      sym_variable_definition_sentence,
      aux_sym_source_file_repeat1,
  [984] = 6,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(190), 1,
      sym_identifier,
    ACTIONS(250), 1,
      sym_integer_literal,
    ACTIONS(252), 2,
      sym_floating_point_literal,
      sym_string_literal,
    STATE(21), 3,
      sym__callable_expression,
      sym_function_call,
      sym_variable_reference_expression,
    STATE(51), 4,
      sym__uncallable_expression,
      sym__expression,
      sym_binary_expresion,
      sym__literal,
  [1009] = 6,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(190), 1,
      sym_identifier,
    ACTIONS(254), 1,
      sym_integer_literal,
    ACTIONS(256), 2,
      sym_floating_point_literal,
      sym_string_literal,
    STATE(21), 3,
      sym__callable_expression,
      sym_function_call,
      sym_variable_reference_expression,
    STATE(37), 4,
      sym__uncallable_expression,
      sym__expression,
      sym_binary_expresion,
      sym__literal,
  [1034] = 7,
    ACTIONS(174), 1,
      anon_sym_EQ_EQ,
    ACTIONS(176), 1,
      anon_sym_EQ,
    ACTIONS(258), 1,
      anon_sym_RPAREN,
    ACTIONS(170), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(172), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(178), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(180), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [1061] = 7,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(190), 1,
      sym_identifier,
    ACTIONS(260), 1,
      sym_integer_literal,
    STATE(54), 1,
      sym__expression,
    ACTIONS(262), 2,
      sym_floating_point_literal,
      sym_string_literal,
    STATE(34), 3,
      sym__callable_expression,
      sym_function_call,
      sym_variable_reference_expression,
    STATE(53), 3,
      sym__uncallable_expression,
      sym_binary_expresion,
      sym__literal,
  [1088] = 3,
    ACTIONS(264), 1,
      anon_sym_RPAREN,
    ACTIONS(148), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
    ACTIONS(146), 8,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [1107] = 6,
    ACTIONS(174), 1,
      anon_sym_EQ_EQ,
    ACTIONS(176), 1,
      anon_sym_EQ,
    ACTIONS(170), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(172), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(178), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(180), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [1131] = 4,
    ACTIONS(266), 1,
      anon_sym_RPAREN,
    STATE(65), 1,
      aux_sym_parameter_list_repeat1,
    STATE(76), 1,
      sym_variable_declaration,
    ACTIONS(7), 2,
      anon_sym_var,
      anon_sym_let,
  [1145] = 1,
    ACTIONS(268), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_EQ,
  [1153] = 1,
    ACTIONS(270), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_EQ,
  [1161] = 1,
    ACTIONS(272), 4,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_var,
      anon_sym_let,
  [1168] = 3,
    STATE(59), 1,
      aux_sym_parameter_list_repeat1,
    STATE(89), 1,
      sym_variable_declaration,
    ACTIONS(274), 2,
      anon_sym_var,
      anon_sym_let,
  [1179] = 1,
    ACTIONS(122), 4,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_var,
      anon_sym_let,
  [1186] = 1,
    ACTIONS(114), 4,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_var,
      anon_sym_let,
  [1193] = 1,
    ACTIONS(118), 4,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_var,
      anon_sym_let,
  [1200] = 1,
    ACTIONS(277), 4,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
  [1207] = 1,
    ACTIONS(126), 4,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_var,
      anon_sym_let,
  [1214] = 3,
    STATE(59), 1,
      aux_sym_parameter_list_repeat1,
    STATE(69), 1,
      sym_variable_declaration,
    ACTIONS(7), 2,
      anon_sym_var,
      anon_sym_let,
  [1225] = 3,
    ACTIONS(166), 1,
      anon_sym_COMMA,
    ACTIONS(279), 1,
      anon_sym_RPAREN,
    STATE(67), 1,
      aux_sym_function_call_repeat1,
  [1235] = 3,
    ACTIONS(206), 1,
      anon_sym_RPAREN,
    ACTIONS(281), 1,
      anon_sym_COMMA,
    STATE(67), 1,
      aux_sym_function_call_repeat1,
  [1245] = 2,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    STATE(12), 1,
      sym_block,
  [1252] = 2,
    ACTIONS(284), 1,
      anon_sym_COMMA,
    ACTIONS(286), 1,
      anon_sym_RPAREN,
  [1259] = 2,
    ACTIONS(288), 1,
      anon_sym_LPAREN,
    STATE(80), 1,
      sym_parameter_list,
  [1266] = 1,
    ACTIONS(290), 2,
      anon_sym_var,
      anon_sym_let,
  [1271] = 2,
    ACTIONS(292), 1,
      anon_sym_LBRACE,
    STATE(58), 1,
      sym_block,
  [1278] = 2,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    STATE(18), 1,
      sym_block,
  [1285] = 2,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    STATE(11), 1,
      sym_block,
  [1292] = 2,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    STATE(17), 1,
      sym_block,
  [1299] = 2,
    ACTIONS(284), 1,
      anon_sym_COMMA,
    ACTIONS(294), 1,
      anon_sym_RPAREN,
  [1306] = 2,
    ACTIONS(296), 1,
      anon_sym_SEMI,
    ACTIONS(298), 1,
      anon_sym_EQ,
  [1313] = 2,
    ACTIONS(298), 1,
      anon_sym_EQ,
    ACTIONS(300), 1,
      anon_sym_SEMI,
  [1320] = 1,
    ACTIONS(302), 1,
      ts_builtin_sym_end,
  [1324] = 1,
    ACTIONS(304), 1,
      anon_sym_DASH_GT,
  [1328] = 1,
    ACTIONS(306), 1,
      anon_sym_SEMI,
  [1332] = 1,
    ACTIONS(308), 1,
      anon_sym_LPAREN,
  [1336] = 1,
    ACTIONS(310), 1,
      sym_identifier,
  [1340] = 1,
    ACTIONS(312), 1,
      anon_sym_LPAREN,
  [1344] = 1,
    ACTIONS(314), 1,
      sym_identifier,
  [1348] = 1,
    ACTIONS(316), 1,
      anon_sym_SEMI,
  [1352] = 1,
    ACTIONS(318), 1,
      anon_sym_COLON,
  [1356] = 1,
    ACTIONS(320), 1,
      anon_sym_DASH_GT,
  [1360] = 1,
    ACTIONS(284), 1,
      anon_sym_COMMA,
  [1364] = 1,
    ACTIONS(322), 1,
      anon_sym_DASH_GT,
  [1368] = 1,
    ACTIONS(324), 1,
      anon_sym_SEMI,
  [1372] = 1,
    ACTIONS(326), 1,
      anon_sym_DASH_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 22,
  [SMALL_STATE(9)] = 44,
  [SMALL_STATE(10)] = 66,
  [SMALL_STATE(11)] = 88,
  [SMALL_STATE(12)] = 110,
  [SMALL_STATE(13)] = 132,
  [SMALL_STATE(14)] = 154,
  [SMALL_STATE(15)] = 176,
  [SMALL_STATE(16)] = 198,
  [SMALL_STATE(17)] = 220,
  [SMALL_STATE(18)] = 242,
  [SMALL_STATE(19)] = 264,
  [SMALL_STATE(20)] = 284,
  [SMALL_STATE(21)] = 304,
  [SMALL_STATE(22)] = 326,
  [SMALL_STATE(23)] = 346,
  [SMALL_STATE(24)] = 366,
  [SMALL_STATE(25)] = 386,
  [SMALL_STATE(26)] = 405,
  [SMALL_STATE(27)] = 438,
  [SMALL_STATE(28)] = 465,
  [SMALL_STATE(29)] = 484,
  [SMALL_STATE(30)] = 505,
  [SMALL_STATE(31)] = 528,
  [SMALL_STATE(32)] = 549,
  [SMALL_STATE(33)] = 570,
  [SMALL_STATE(34)] = 598,
  [SMALL_STATE(35)] = 620,
  [SMALL_STATE(36)] = 648,
  [SMALL_STATE(37)] = 676,
  [SMALL_STATE(38)] = 703,
  [SMALL_STATE(39)] = 728,
  [SMALL_STATE(40)] = 753,
  [SMALL_STATE(41)] = 778,
  [SMALL_STATE(42)] = 803,
  [SMALL_STATE(43)] = 828,
  [SMALL_STATE(44)] = 853,
  [SMALL_STATE(45)] = 880,
  [SMALL_STATE(46)] = 905,
  [SMALL_STATE(47)] = 932,
  [SMALL_STATE(48)] = 959,
  [SMALL_STATE(49)] = 984,
  [SMALL_STATE(50)] = 1009,
  [SMALL_STATE(51)] = 1034,
  [SMALL_STATE(52)] = 1061,
  [SMALL_STATE(53)] = 1088,
  [SMALL_STATE(54)] = 1107,
  [SMALL_STATE(55)] = 1131,
  [SMALL_STATE(56)] = 1145,
  [SMALL_STATE(57)] = 1153,
  [SMALL_STATE(58)] = 1161,
  [SMALL_STATE(59)] = 1168,
  [SMALL_STATE(60)] = 1179,
  [SMALL_STATE(61)] = 1186,
  [SMALL_STATE(62)] = 1193,
  [SMALL_STATE(63)] = 1200,
  [SMALL_STATE(64)] = 1207,
  [SMALL_STATE(65)] = 1214,
  [SMALL_STATE(66)] = 1225,
  [SMALL_STATE(67)] = 1235,
  [SMALL_STATE(68)] = 1245,
  [SMALL_STATE(69)] = 1252,
  [SMALL_STATE(70)] = 1259,
  [SMALL_STATE(71)] = 1266,
  [SMALL_STATE(72)] = 1271,
  [SMALL_STATE(73)] = 1278,
  [SMALL_STATE(74)] = 1285,
  [SMALL_STATE(75)] = 1292,
  [SMALL_STATE(76)] = 1299,
  [SMALL_STATE(77)] = 1306,
  [SMALL_STATE(78)] = 1313,
  [SMALL_STATE(79)] = 1320,
  [SMALL_STATE(80)] = 1324,
  [SMALL_STATE(81)] = 1328,
  [SMALL_STATE(82)] = 1332,
  [SMALL_STATE(83)] = 1336,
  [SMALL_STATE(84)] = 1340,
  [SMALL_STATE(85)] = 1344,
  [SMALL_STATE(86)] = 1348,
  [SMALL_STATE(87)] = 1352,
  [SMALL_STATE(88)] = 1356,
  [SMALL_STATE(89)] = 1360,
  [SMALL_STATE(90)] = 1364,
  [SMALL_STATE(91)] = 1368,
  [SMALL_STATE(92)] = 1372,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [81] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_sentence, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_sentence, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_break_sentence, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_break_sentence, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_sentence, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_sentence, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_sentence, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_sentence, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_statement, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_statement, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_elif_statement, 5, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elif_statement, 5, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration_sentence, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration_sentence, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_definition_sentence, 2, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_definition_sentence, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 5, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_loop_statement, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_loop_statement, 2, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_reference_expression, 1, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_reference_expression, 1, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__callable_expression, 3, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__callable_expression, 3, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 5, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 5, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expresion, 3, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expresion, 3, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__uncallable_expression, 3, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__uncallable_expression, 3, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [210] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [214] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [218] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [228] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [234] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_definition, 3, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [244] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [247] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [250] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [254] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [260] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_builtin_type, 1, 0, 0),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_user_type, 1, 0, 0),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 6, 0, 2),
  [274] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 4, 0, 1),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [281] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [302] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 4, 0, 0),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [326] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_garnet(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "garnet",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
