/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 57
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 60
#define ALIAS_COUNT 0
#define TOKEN_COUNT 36
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_func = 1,
  anon_sym_DASH_GT = 2,
  sym_identifier = 3,
  anon_sym_LPAREN = 4,
  anon_sym_COMMA = 5,
  anon_sym_RPAREN = 6,
  anon_sym_u8 = 7,
  anon_sym_i8 = 8,
  anon_sym_u16 = 9,
  anon_sym_i16 = 10,
  anon_sym_u32 = 11,
  anon_sym_i32 = 12,
  anon_sym_u64 = 13,
  anon_sym_i64 = 14,
  anon_sym_f32 = 15,
  anon_sym_f64 = 16,
  anon_sym_LBRACE = 17,
  anon_sym_RBRACE = 18,
  sym_oneline_comment = 19,
  sym_multiline_comment = 20,
  anon_sym_SEMI = 21,
  anon_sym_LT = 22,
  anon_sym_GT = 23,
  anon_sym_EQ = 24,
  anon_sym_PLUS = 25,
  anon_sym_DASH = 26,
  anon_sym_STAR = 27,
  anon_sym_SLASH = 28,
  anon_sym_PERCENT = 29,
  sym_integer_literal = 30,
  sym_floating_point_literal = 31,
  anon_sym_var = 32,
  anon_sym_let = 33,
  anon_sym_COLON = 34,
  anon_sym_return = 35,
  sym_source_file = 36,
  sym__definition = 37,
  sym__declaration = 38,
  sym_function_definition = 39,
  sym_parameter_list = 40,
  sym__type = 41,
  sym_builtin_type = 42,
  sym_user_type = 43,
  sym_block = 44,
  sym__comment = 45,
  sym__sentence = 46,
  sym_expression_sentence = 47,
  sym_variable_declaration_sentence = 48,
  sym_variable_definition_sentence = 49,
  sym__expression = 50,
  sym_binary_expresion = 51,
  sym__literal = 52,
  sym_variable_reference_expression = 53,
  sym_variable_declaration = 54,
  sym_variable_definition = 55,
  sym_return_sentence = 56,
  aux_sym_source_file_repeat1 = 57,
  aux_sym_parameter_list_repeat1 = 58,
  aux_sym_block_repeat1 = 59,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_func] = "func",
  [anon_sym_DASH_GT] = "->",
  [sym_identifier] = "identifier",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_u8] = "u8",
  [anon_sym_i8] = "i8",
  [anon_sym_u16] = "u16",
  [anon_sym_i16] = "i16",
  [anon_sym_u32] = "u32",
  [anon_sym_i32] = "i32",
  [anon_sym_u64] = "u64",
  [anon_sym_i64] = "i64",
  [anon_sym_f32] = "f32",
  [anon_sym_f64] = "f64",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_oneline_comment] = "oneline_comment",
  [sym_multiline_comment] = "multiline_comment",
  [anon_sym_SEMI] = ";",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_EQ] = "=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [sym_integer_literal] = "integer_literal",
  [sym_floating_point_literal] = "floating_point_literal",
  [anon_sym_var] = "var",
  [anon_sym_let] = "let",
  [anon_sym_COLON] = ":",
  [anon_sym_return] = "return",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym__declaration] = "_declaration",
  [sym_function_definition] = "function_definition",
  [sym_parameter_list] = "parameter_list",
  [sym__type] = "_type",
  [sym_builtin_type] = "builtin_type",
  [sym_user_type] = "user_type",
  [sym_block] = "block",
  [sym__comment] = "_comment",
  [sym__sentence] = "_sentence",
  [sym_expression_sentence] = "expression_sentence",
  [sym_variable_declaration_sentence] = "variable_declaration_sentence",
  [sym_variable_definition_sentence] = "variable_definition_sentence",
  [sym__expression] = "_expression",
  [sym_binary_expresion] = "binary_expresion",
  [sym__literal] = "_literal",
  [sym_variable_reference_expression] = "variable_reference_expression",
  [sym_variable_declaration] = "variable_declaration",
  [sym_variable_definition] = "variable_definition",
  [sym_return_sentence] = "return_sentence",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_func] = anon_sym_func,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [sym_identifier] = sym_identifier,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_u8] = anon_sym_u8,
  [anon_sym_i8] = anon_sym_i8,
  [anon_sym_u16] = anon_sym_u16,
  [anon_sym_i16] = anon_sym_i16,
  [anon_sym_u32] = anon_sym_u32,
  [anon_sym_i32] = anon_sym_i32,
  [anon_sym_u64] = anon_sym_u64,
  [anon_sym_i64] = anon_sym_i64,
  [anon_sym_f32] = anon_sym_f32,
  [anon_sym_f64] = anon_sym_f64,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_oneline_comment] = sym_oneline_comment,
  [sym_multiline_comment] = sym_multiline_comment,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [sym_integer_literal] = sym_integer_literal,
  [sym_floating_point_literal] = sym_floating_point_literal,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_return] = anon_sym_return,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym__declaration] = sym__declaration,
  [sym_function_definition] = sym_function_definition,
  [sym_parameter_list] = sym_parameter_list,
  [sym__type] = sym__type,
  [sym_builtin_type] = sym_builtin_type,
  [sym_user_type] = sym_user_type,
  [sym_block] = sym_block,
  [sym__comment] = sym__comment,
  [sym__sentence] = sym__sentence,
  [sym_expression_sentence] = sym_expression_sentence,
  [sym_variable_declaration_sentence] = sym_variable_declaration_sentence,
  [sym_variable_definition_sentence] = sym_variable_definition_sentence,
  [sym__expression] = sym__expression,
  [sym_binary_expresion] = sym_binary_expresion,
  [sym__literal] = sym__literal,
  [sym_variable_reference_expression] = sym_variable_reference_expression,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_variable_definition] = sym_variable_definition,
  [sym_return_sentence] = sym_return_sentence,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_func] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_oneline_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_multiline_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_floating_point_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_builtin_type] = {
    .visible = true,
    .named = true,
  },
  [sym_user_type] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__comment] = {
    .visible = false,
    .named = true,
  },
  [sym__sentence] = {
    .visible = false,
    .named = true,
  },
  [sym_expression_sentence] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration_sentence] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_definition_sentence] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expresion] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_variable_reference_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_return_sentence] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_name = 2,
  field_parameters = 3,
  field_return_type = 4,
  field_type = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_name] = "name",
  [field_parameters] = "parameters",
  [field_return_type] = "return_type",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
    {field_type, 3},
  [2] =
    {field_body, 5},
    {field_name, 1},
    {field_parameters, 2},
    {field_return_type, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 20,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 21,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 41,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 50,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(30);
      ADVANCE_MAP(
        '#', 81,
        '%', 93,
        '(', 54,
        ')', 56,
        '*', 91,
        '+', 88,
        ',', 55,
        '-', 90,
        '/', 92,
        ':', 100,
        ';', 84,
        '<', 85,
        '=', 87,
        '>', 86,
        'f', 10,
        'i', 5,
        'l', 20,
        'r', 21,
        'u', 6,
        'v', 18,
        '{', 77,
        '}', 78,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(94);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '#', 81,
        '%', 93,
        '*', 91,
        '+', 88,
        '-', 89,
        '/', 92,
        ';', 84,
        '<', 85,
        '=', 87,
        '>', 86,
        'l', 45,
        'r', 46,
        'v', 44,
        '}', 78,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(94);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(83);
      if (lookahead == '*') ADVANCE(2);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(2);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == 'f') ADVANCE(38);
      if (lookahead == 'i') ADVANCE(33);
      if (lookahead == 'u') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 5:
      if (lookahead == '1') ADVANCE(14);
      if (lookahead == '3') ADVANCE(8);
      if (lookahead == '6') ADVANCE(12);
      if (lookahead == '8') ADVANCE(59);
      END_STATE();
    case 6:
      if (lookahead == '1') ADVANCE(15);
      if (lookahead == '3') ADVANCE(9);
      if (lookahead == '6') ADVANCE(13);
      if (lookahead == '8') ADVANCE(57);
      END_STATE();
    case 7:
      if (lookahead == '2') ADVANCE(73);
      END_STATE();
    case 8:
      if (lookahead == '2') ADVANCE(67);
      END_STATE();
    case 9:
      if (lookahead == '2') ADVANCE(65);
      END_STATE();
    case 10:
      if (lookahead == '3') ADVANCE(7);
      if (lookahead == '6') ADVANCE(11);
      if (lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == '4') ADVANCE(75);
      END_STATE();
    case 12:
      if (lookahead == '4') ADVANCE(71);
      END_STATE();
    case 13:
      if (lookahead == '4') ADVANCE(69);
      END_STATE();
    case 14:
      if (lookahead == '6') ADVANCE(63);
      END_STATE();
    case 15:
      if (lookahead == '6') ADVANCE(61);
      END_STATE();
    case 16:
      if (lookahead == ';') ADVANCE(84);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(94);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 17:
      if (lookahead == '>') ADVANCE(32);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(24);
      END_STATE();
    case 19:
      if (lookahead == 'c') ADVANCE(31);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(101);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(96);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(98);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 28:
      if (lookahead == 'u') ADVANCE(25);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(95);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_func);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '1') ADVANCE(42);
      if (lookahead == '3') ADVANCE(36);
      if (lookahead == '6') ADVANCE(40);
      if (lookahead == '8') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '1') ADVANCE(43);
      if (lookahead == '3') ADVANCE(37);
      if (lookahead == '6') ADVANCE(41);
      if (lookahead == '8') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '2') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '2') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '2') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '3') ADVANCE(35);
      if (lookahead == '6') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '4') ADVANCE(76);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '4') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '4') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '6') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '6') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(97);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(99);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_u8);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_u8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_i8);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_i8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_u16);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_u16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_i16);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_i16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_u32);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_u32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_i32);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_i32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_u64);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_u64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_i64);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_i64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_f32);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_f32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_f64);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_f64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_oneline_comment);
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead == '#') ADVANCE(80);
      if (lookahead == '*') ADVANCE(79);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_oneline_comment);
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead == '*') ADVANCE(79);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_oneline_comment);
      if (lookahead == '*') ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(82);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_oneline_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_multiline_comment);
      if (lookahead == '*') ADVANCE(2);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(32);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(94);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_floating_point_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(95);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_var);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 16},
  [23] = {.lex_state = 16},
  [24] = {.lex_state = 16},
  [25] = {.lex_state = 16},
  [26] = {.lex_state = 16},
  [27] = {.lex_state = 16},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 4},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 4},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 16},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 16},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 4},
  [56] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_func] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_u8] = ACTIONS(1),
    [anon_sym_i8] = ACTIONS(1),
    [anon_sym_u16] = ACTIONS(1),
    [anon_sym_i16] = ACTIONS(1),
    [anon_sym_u32] = ACTIONS(1),
    [anon_sym_i32] = ACTIONS(1),
    [anon_sym_u64] = ACTIONS(1),
    [anon_sym_i64] = ACTIONS(1),
    [anon_sym_f32] = ACTIONS(1),
    [anon_sym_f64] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_oneline_comment] = ACTIONS(1),
    [sym_multiline_comment] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
    [sym_floating_point_literal] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(47),
    [sym__definition] = STATE(8),
    [sym__declaration] = STATE(8),
    [sym_function_definition] = STATE(8),
    [sym_variable_declaration_sentence] = STATE(8),
    [sym_variable_definition_sentence] = STATE(8),
    [sym_variable_declaration] = STATE(41),
    [sym_variable_definition] = STATE(50),
    [aux_sym_source_file_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_func] = ACTIONS(5),
    [anon_sym_var] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_RBRACE,
    ACTIONS(15), 1,
      sym_integer_literal,
    ACTIONS(17), 1,
      sym_floating_point_literal,
    ACTIONS(21), 1,
      anon_sym_return,
    STATE(43), 1,
      sym_variable_declaration,
    STATE(56), 1,
      sym_variable_definition,
    ACTIONS(13), 2,
      sym_oneline_comment,
      sym_multiline_comment,
    ACTIONS(19), 2,
      anon_sym_var,
      anon_sym_let,
    STATE(17), 4,
      sym__expression,
      sym_binary_expresion,
      sym__literal,
      sym_variable_reference_expression,
    STATE(3), 7,
      sym__comment,
      sym__sentence,
      sym_expression_sentence,
      sym_variable_declaration_sentence,
      sym_variable_definition_sentence,
      sym_return_sentence,
      aux_sym_block_repeat1,
  [45] = 11,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_integer_literal,
    ACTIONS(17), 1,
      sym_floating_point_literal,
    ACTIONS(21), 1,
      anon_sym_return,
    ACTIONS(23), 1,
      anon_sym_RBRACE,
    STATE(43), 1,
      sym_variable_declaration,
    STATE(56), 1,
      sym_variable_definition,
    ACTIONS(19), 2,
      anon_sym_var,
      anon_sym_let,
    ACTIONS(25), 2,
      sym_oneline_comment,
      sym_multiline_comment,
    STATE(17), 4,
      sym__expression,
      sym_binary_expresion,
      sym__literal,
      sym_variable_reference_expression,
    STATE(4), 7,
      sym__comment,
      sym__sentence,
      sym_expression_sentence,
      sym_variable_declaration_sentence,
      sym_variable_definition_sentence,
      sym_return_sentence,
      aux_sym_block_repeat1,
  [90] = 11,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(30), 1,
      anon_sym_RBRACE,
    ACTIONS(35), 1,
      sym_integer_literal,
    ACTIONS(38), 1,
      sym_floating_point_literal,
    ACTIONS(44), 1,
      anon_sym_return,
    STATE(43), 1,
      sym_variable_declaration,
    STATE(56), 1,
      sym_variable_definition,
    ACTIONS(32), 2,
      sym_oneline_comment,
      sym_multiline_comment,
    ACTIONS(41), 2,
      anon_sym_var,
      anon_sym_let,
    STATE(17), 4,
      sym__expression,
      sym_binary_expresion,
      sym__literal,
      sym_variable_reference_expression,
    STATE(4), 7,
      sym__comment,
      sym__sentence,
      sym_expression_sentence,
      sym_variable_declaration_sentence,
      sym_variable_definition_sentence,
      sym_return_sentence,
      aux_sym_block_repeat1,
  [135] = 3,
    ACTIONS(47), 1,
      sym_identifier,
    STATE(36), 3,
      sym__type,
      sym_builtin_type,
      sym_user_type,
    ACTIONS(49), 10,
      anon_sym_u8,
      anon_sym_i8,
      anon_sym_u16,
      anon_sym_i16,
      anon_sym_u32,
      anon_sym_i32,
      anon_sym_u64,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
  [156] = 3,
    ACTIONS(47), 1,
      sym_identifier,
    STATE(39), 3,
      sym__type,
      sym_builtin_type,
      sym_user_type,
    ACTIONS(49), 10,
      anon_sym_u8,
      anon_sym_i8,
      anon_sym_u16,
      anon_sym_i16,
      anon_sym_u32,
      anon_sym_i32,
      anon_sym_u64,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
  [177] = 6,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      anon_sym_func,
    STATE(41), 1,
      sym_variable_declaration,
    STATE(50), 1,
      sym_variable_definition,
    ACTIONS(56), 2,
      anon_sym_var,
      anon_sym_let,
    STATE(7), 6,
      sym__definition,
      sym__declaration,
      sym_function_definition,
      sym_variable_declaration_sentence,
      sym_variable_definition_sentence,
      aux_sym_source_file_repeat1,
  [202] = 6,
    ACTIONS(5), 1,
      anon_sym_func,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    STATE(41), 1,
      sym_variable_declaration,
    STATE(50), 1,
      sym_variable_definition,
    ACTIONS(7), 2,
      anon_sym_var,
      anon_sym_let,
    STATE(7), 6,
      sym__definition,
      sym__declaration,
      sym_function_definition,
      sym_variable_declaration_sentence,
      sym_variable_definition_sentence,
      aux_sym_source_file_repeat1,
  [227] = 2,
    ACTIONS(63), 2,
      anon_sym_RBRACE,
      sym_floating_point_literal,
    ACTIONS(61), 7,
      sym_identifier,
      sym_oneline_comment,
      sym_multiline_comment,
      sym_integer_literal,
      anon_sym_var,
      anon_sym_let,
      anon_sym_return,
  [241] = 5,
    ACTIONS(65), 1,
      anon_sym_SEMI,
    ACTIONS(69), 1,
      anon_sym_EQ,
    ACTIONS(67), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(71), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(73), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [261] = 1,
    ACTIONS(75), 9,
      anon_sym_SEMI,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [273] = 4,
    ACTIONS(69), 1,
      anon_sym_EQ,
    ACTIONS(71), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(73), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(77), 3,
      anon_sym_SEMI,
      anon_sym_LT,
      anon_sym_GT,
  [291] = 3,
    ACTIONS(71), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(73), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(77), 4,
      anon_sym_SEMI,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
  [307] = 2,
    ACTIONS(73), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(77), 6,
      anon_sym_SEMI,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
  [321] = 1,
    ACTIONS(77), 9,
      anon_sym_SEMI,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [333] = 2,
    ACTIONS(81), 2,
      anon_sym_RBRACE,
      sym_floating_point_literal,
    ACTIONS(79), 7,
      sym_identifier,
      sym_oneline_comment,
      sym_multiline_comment,
      sym_integer_literal,
      anon_sym_var,
      anon_sym_let,
      anon_sym_return,
  [347] = 5,
    ACTIONS(69), 1,
      anon_sym_EQ,
    ACTIONS(83), 1,
      anon_sym_SEMI,
    ACTIONS(67), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(71), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(73), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [367] = 2,
    ACTIONS(87), 2,
      anon_sym_RBRACE,
      sym_floating_point_literal,
    ACTIONS(85), 7,
      sym_identifier,
      sym_oneline_comment,
      sym_multiline_comment,
      sym_integer_literal,
      anon_sym_var,
      anon_sym_let,
      anon_sym_return,
  [381] = 5,
    ACTIONS(69), 1,
      anon_sym_EQ,
    ACTIONS(89), 1,
      anon_sym_SEMI,
    ACTIONS(67), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(71), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(73), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [401] = 2,
    ACTIONS(93), 2,
      anon_sym_RBRACE,
      sym_floating_point_literal,
    ACTIONS(91), 7,
      sym_identifier,
      sym_oneline_comment,
      sym_multiline_comment,
      sym_integer_literal,
      anon_sym_var,
      anon_sym_let,
      anon_sym_return,
  [415] = 2,
    ACTIONS(97), 2,
      anon_sym_RBRACE,
      sym_floating_point_literal,
    ACTIONS(95), 7,
      sym_identifier,
      sym_oneline_comment,
      sym_multiline_comment,
      sym_integer_literal,
      anon_sym_var,
      anon_sym_let,
      anon_sym_return,
  [429] = 5,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(101), 1,
      anon_sym_SEMI,
    ACTIONS(103), 1,
      sym_integer_literal,
    ACTIONS(105), 1,
      sym_floating_point_literal,
    STATE(19), 4,
      sym__expression,
      sym_binary_expresion,
      sym__literal,
      sym_variable_reference_expression,
  [448] = 4,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(107), 1,
      sym_integer_literal,
    ACTIONS(109), 1,
      sym_floating_point_literal,
    STATE(13), 4,
      sym__expression,
      sym_binary_expresion,
      sym__literal,
      sym_variable_reference_expression,
  [464] = 4,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(111), 1,
      sym_integer_literal,
    ACTIONS(113), 1,
      sym_floating_point_literal,
    STATE(10), 4,
      sym__expression,
      sym_binary_expresion,
      sym__literal,
      sym_variable_reference_expression,
  [480] = 4,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(115), 1,
      sym_integer_literal,
    ACTIONS(117), 1,
      sym_floating_point_literal,
    STATE(14), 4,
      sym__expression,
      sym_binary_expresion,
      sym__literal,
      sym_variable_reference_expression,
  [496] = 4,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(119), 1,
      sym_integer_literal,
    ACTIONS(121), 1,
      sym_floating_point_literal,
    STATE(12), 4,
      sym__expression,
      sym_binary_expresion,
      sym__literal,
      sym_variable_reference_expression,
  [512] = 4,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(123), 1,
      sym_integer_literal,
    ACTIONS(125), 1,
      sym_floating_point_literal,
    STATE(15), 4,
      sym__expression,
      sym_binary_expresion,
      sym__literal,
      sym_variable_reference_expression,
  [528] = 1,
    ACTIONS(127), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_EQ,
  [536] = 4,
    ACTIONS(129), 1,
      anon_sym_RPAREN,
    STATE(32), 1,
      aux_sym_parameter_list_repeat1,
    STATE(45), 1,
      sym_variable_declaration,
    ACTIONS(7), 2,
      anon_sym_var,
      anon_sym_let,
  [550] = 1,
    ACTIONS(131), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_EQ,
  [558] = 1,
    ACTIONS(93), 4,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_var,
      anon_sym_let,
  [565] = 3,
    STATE(33), 1,
      aux_sym_parameter_list_repeat1,
    STATE(40), 1,
      sym_variable_declaration,
    ACTIONS(7), 2,
      anon_sym_var,
      anon_sym_let,
  [576] = 3,
    STATE(33), 1,
      aux_sym_parameter_list_repeat1,
    STATE(49), 1,
      sym_variable_declaration,
    ACTIONS(133), 2,
      anon_sym_var,
      anon_sym_let,
  [587] = 1,
    ACTIONS(136), 4,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_var,
      anon_sym_let,
  [594] = 1,
    ACTIONS(138), 4,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_var,
      anon_sym_let,
  [601] = 1,
    ACTIONS(140), 4,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
  [608] = 1,
    ACTIONS(142), 4,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_var,
      anon_sym_let,
  [615] = 1,
    ACTIONS(97), 4,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_var,
      anon_sym_let,
  [622] = 2,
    ACTIONS(144), 1,
      anon_sym_LBRACE,
    STATE(34), 1,
      sym_block,
  [629] = 2,
    ACTIONS(146), 1,
      anon_sym_COMMA,
    ACTIONS(148), 1,
      anon_sym_RPAREN,
  [636] = 2,
    ACTIONS(150), 1,
      anon_sym_SEMI,
    ACTIONS(152), 1,
      anon_sym_EQ,
  [643] = 1,
    ACTIONS(154), 2,
      anon_sym_var,
      anon_sym_let,
  [648] = 2,
    ACTIONS(152), 1,
      anon_sym_EQ,
    ACTIONS(156), 1,
      anon_sym_SEMI,
  [655] = 2,
    ACTIONS(158), 1,
      anon_sym_LPAREN,
    STATE(46), 1,
      sym_parameter_list,
  [662] = 2,
    ACTIONS(146), 1,
      anon_sym_COMMA,
    ACTIONS(160), 1,
      anon_sym_RPAREN,
  [669] = 1,
    ACTIONS(162), 1,
      anon_sym_DASH_GT,
  [673] = 1,
    ACTIONS(164), 1,
      ts_builtin_sym_end,
  [677] = 1,
    ACTIONS(166), 1,
      anon_sym_DASH_GT,
  [681] = 1,
    ACTIONS(146), 1,
      anon_sym_COMMA,
  [685] = 1,
    ACTIONS(168), 1,
      anon_sym_SEMI,
  [689] = 1,
    ACTIONS(170), 1,
      sym_identifier,
  [693] = 1,
    ACTIONS(172), 1,
      anon_sym_COLON,
  [697] = 1,
    ACTIONS(174), 1,
      sym_identifier,
  [701] = 1,
    ACTIONS(176), 1,
      anon_sym_DASH_GT,
  [705] = 1,
    ACTIONS(178), 1,
      anon_sym_DASH_GT,
  [709] = 1,
    ACTIONS(180), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 45,
  [SMALL_STATE(4)] = 90,
  [SMALL_STATE(5)] = 135,
  [SMALL_STATE(6)] = 156,
  [SMALL_STATE(7)] = 177,
  [SMALL_STATE(8)] = 202,
  [SMALL_STATE(9)] = 227,
  [SMALL_STATE(10)] = 241,
  [SMALL_STATE(11)] = 261,
  [SMALL_STATE(12)] = 273,
  [SMALL_STATE(13)] = 291,
  [SMALL_STATE(14)] = 307,
  [SMALL_STATE(15)] = 321,
  [SMALL_STATE(16)] = 333,
  [SMALL_STATE(17)] = 347,
  [SMALL_STATE(18)] = 367,
  [SMALL_STATE(19)] = 381,
  [SMALL_STATE(20)] = 401,
  [SMALL_STATE(21)] = 415,
  [SMALL_STATE(22)] = 429,
  [SMALL_STATE(23)] = 448,
  [SMALL_STATE(24)] = 464,
  [SMALL_STATE(25)] = 480,
  [SMALL_STATE(26)] = 496,
  [SMALL_STATE(27)] = 512,
  [SMALL_STATE(28)] = 528,
  [SMALL_STATE(29)] = 536,
  [SMALL_STATE(30)] = 550,
  [SMALL_STATE(31)] = 558,
  [SMALL_STATE(32)] = 565,
  [SMALL_STATE(33)] = 576,
  [SMALL_STATE(34)] = 587,
  [SMALL_STATE(35)] = 594,
  [SMALL_STATE(36)] = 601,
  [SMALL_STATE(37)] = 608,
  [SMALL_STATE(38)] = 615,
  [SMALL_STATE(39)] = 622,
  [SMALL_STATE(40)] = 629,
  [SMALL_STATE(41)] = 636,
  [SMALL_STATE(42)] = 643,
  [SMALL_STATE(43)] = 648,
  [SMALL_STATE(44)] = 655,
  [SMALL_STATE(45)] = 662,
  [SMALL_STATE(46)] = 669,
  [SMALL_STATE(47)] = 673,
  [SMALL_STATE(48)] = 677,
  [SMALL_STATE(49)] = 681,
  [SMALL_STATE(50)] = 685,
  [SMALL_STATE(51)] = 689,
  [SMALL_STATE(52)] = 693,
  [SMALL_STATE(53)] = 697,
  [SMALL_STATE(54)] = 701,
  [SMALL_STATE(55)] = 705,
  [SMALL_STATE(56)] = 709,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_sentence, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_sentence, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_definition, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_reference_expression, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expresion, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_sentence, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_sentence, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_sentence, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_sentence, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration_sentence, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration_sentence, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_definition_sentence, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_definition_sentence, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_builtin_type, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_user_type, 1, 0, 0),
  [133] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 6, 0, 2),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 4, 0, 1),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [164] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 4, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_garnet(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "garnet",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
